name: CI

on: 
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
            miniconda-version: "latest"
            python-version: ${{ matrix.python-version }}

      - name: Install source
        shell: bash -l {0}
        run: python -m pip install .[all]

      - name: List installed packages
        shell: bash -l {0}
        run: conda list

      - name: Run tests
        shell: bash -l {0}
        run: pytest